export const abi = [
  'event GaslessActionExecuted(address indexed user,uint8 indexed action,address indexed relayer)',
  'event FeePaid(address indexed user,uint256 amount,bool paidFromPublicBalance)',
  'event EthSent(address indexed user,uint256 amount)',
  'event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)',
  'function ETH_amount_sent_to_users() view returns (uint256)',
  'function FEE() view returns (uint256)',
  'function NAME() view returns (string)',
  'function VERSION() view returns (string)',
  'function Swap_BV3_for_ETH()',
  'function Part_I(address privacyContractAddress,uint256[] encryptedArray)',
  'function Part_II(address privacyContractAddress,uint256[] encryptedArray)',
  'function executeSwapBV3ForETH(address user,uint256 deadline,bytes signature)',
  'function executePartI(address user,address privacyContractAddress,uint256[] encryptedArray,uint256 deadline,bytes signature)',
  'function executePartII(address user,address privacyContractAddress,uint256[] encryptedArray,uint256 deadline,bytes signature)',
  'function fee_paid(address user) view returns (bool)',
  'function nonces(address user) view returns (uint256)',
  'function domainSeparator() view returns (bytes32)',
  'function gaslessDigest(address user,address privacyContractAddress,bytes32 encryptedArrayHash,uint8 action,uint256 nonce,uint256 deadline) view returns (bytes32)',
  'function owner() view returns (address)',
  'function getOwner() view returns (address)',
  'function setAddressRegistry(address newAddressRegistry)',
  'function setBV3Address(address _bv3Address)',
  'function setETHSendOut(uint256 _amount)',
  'function setFee(uint256 _newFee)',
  'function totalETHDeposited() view returns (uint256)',
  'function transferOwnership(address newOwner)',
  'function renounceOwnership()',
  'function withdrawBV3Tokens()',
  'function withdrawETH(uint256 amount)',
] as const;

// There is no deployed GSN contract for the current protocol release.
// Keep this environment-only so a future deployment must be configured explicitly.
export const address = process.env.NEXT_PUBLIC_GSN_ADDRESS || '';
